[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
md-5 = "0.10.6"
regex = "1.11.1"
log = "0.4.22"
env_logger = "0.11.5"
aoc = { path = "../utils/rust", version = "0.1.1" }

[[bin]]
name = "one"
path = "src/one.rs"

[[bin]]
name = "two"
path = "src/two.rs"
